"use client";

import { FinancialReportChart } from "@/components/financial-report-chart";
import { Header } from "@/components/header";
import { Button, Card } from "@/components/ui";
import { financial2024 } from "@/lib/financial-2024";
import { rupiah } from "@/lib/utils";
import { Download, ExternalLink, TrendingUp } from "lucide-react";

const percent = (value: number) => new Intl.NumberFormat("id-ID", { style: "percent", maximumFractionDigits: 1 }).format(value);

export default function ReportsPage() {
  const maxExpense = financial2024.expenseCategories[0].amount;
  return <><Header title="Laporan Keuangan" subtitle="Laporan historis PT. Growth Hive Indonesia."/>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-teal-100 bg-teal-50/70 p-4 text-sm dark:border-teal-900 dark:bg-teal-950/30"><div><p className="font-black text-teal-800 dark:text-teal-200">Data aktual 2024</p><p className="mt-1 text-xs text-teal-700/70 dark:text-teal-300/70">Periode {financial2024.period} · Sumber: {financial2024.source}</p></div><div className="flex gap-2"><a href={financial2024.sourceUrl} target="_blank" rel="noreferrer"><Button variant="outline"><ExternalLink size={15}/>Buka sumber</Button></a><Button variant="outline" onClick={() => window.print()}><Download size={15}/>Cetak / Ekspor PDF</Button></div></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Total Pendapatan</p><p className="mt-3 text-xl font-black">{rupiah(financial2024.revenue)}</p><p className="mt-2 text-xs text-slate-400">Feb - Des 2024</p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Total Biaya</p><p className="mt-3 text-xl font-black">{rupiah(financial2024.totalExpenses)}</p><p className="mt-2 text-xs text-slate-400">{percent(financial2024.totalExpenses / financial2024.revenue)} dari pendapatan</p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Laba Usaha</p><p className="mt-3 text-xl font-black">{rupiah(financial2024.operatingProfit)}</p><p className="mt-2 text-xs text-slate-400">Sebelum pajak final</p></Card><Card className="bg-ink p-5 text-white dark:bg-teal-800"><p className="text-xs font-bold uppercase tracking-wider text-teal-200">Net Income</p><p className="mt-3 text-xl font-black">{rupiah(financial2024.netIncome)}</p><p className="mt-2 flex items-center gap-1 text-xs font-bold text-teal-200"><TrendingUp size={13}/>Margin {percent(financial2024.netMargin)}</p></Card></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card className="p-5"><h2 className="font-black">Tren Pendapatan & Net Income</h2><p className="mb-3 text-xs text-slate-400">Performa bulanan tahun 2024</p><FinancialReportChart/></Card><Card className="p-5"><h2 className="font-black">Ringkasan P&L</h2><p className="mb-4 text-xs text-slate-400">Akumulasi {financial2024.period}</p>{[["Pendapatan Usaha",financial2024.revenue],["HPP",financial2024.costOfRevenue],["Biaya Operasional",financial2024.operatingExpenses],["Total Biaya",financial2024.totalExpenses],["Laba Usaha",financial2024.operatingProfit],["Pajak Final",financial2024.tax],["Net Income",financial2024.netIncome]].map(([label,value],index) => <div key={String(label)} className={`flex justify-between border-b border-slate-100 py-3 text-xs dark:border-slate-800 ${index >= 3 ? "font-black" : ""}`}><span>{label}</span><span className={index === 6 ? "text-teal-700" : ""}>{rupiah(Number(value))}</span></div>)}</Card></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_1fr]"><Card className="p-5"><h2 className="font-black">Komposisi Biaya</h2><p className="mb-5 text-xs text-slate-400">Kategori pengeluaran terbesar tahun 2024</p><div className="space-y-4">{financial2024.expenseCategories.map(item => <div key={item.label}><div className="mb-1.5 flex justify-between gap-4 text-xs"><span className="font-semibold">{item.label}</span><span className="shrink-0 font-black">{rupiah(item.amount)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-teal-600" style={{ width: `${Math.max(1, item.amount / maxExpense * 100)}%` }}/></div></div>)}</div></Card><Card className="p-5"><h2 className="font-black">Balance Sheet</h2><p className="mb-4 text-xs text-slate-400">Posisi per Desember 2024</p>{[["Kas & Setara Kas",financial2024.balanceSheet.cash],["Piutang Usaha",financial2024.balanceSheet.receivables],["Pajak Dibayar Dimuka",financial2024.balanceSheet.prepaidTax],["Total Aktiva",financial2024.balanceSheet.totalAssets],["Modal",financial2024.balanceSheet.capital],["Laba Periode Berjalan",financial2024.balanceSheet.currentProfit],["Dividen",financial2024.balanceSheet.dividend],["Total Pasiva",financial2024.balanceSheet.totalLiabilitiesEquity]].map(([label,value],index) => <div key={String(label)} className={`flex justify-between border-b border-slate-100 py-3 text-xs dark:border-slate-800 ${index === 3 || index === 7 ? "font-black text-teal-700" : ""}`}><span>{label}</span><span>{Number(value) < 0 ? "-" : ""}{rupiah(Math.abs(Number(value)))}</span></div>)}</Card></section>
  </>;
}
